services:
  mariadb:
    image: mariadb
    build:
      context:  requirements/mariadb/
    restart: on-failure
  wordpress:
    image: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress/
    ports:
      - "9000:9000"
  nginx:
    depends_on:
      - wordpress
    image: nginx
    build:
      context:  requirements/nginx/
    ports: 
      - "443:443"
    restart: on-failure