volumes:
  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
            device: /home/dani/data/wordpress
            o: bind
            type: none
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
            device: /home/dani/data/mariadb
            o: bind
            type: none
networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: requirements/mariadb/
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env 
    volumes:
      - mariadb_vol:/var/lib/mysql 
  wordpress:
    container_name: wordpress
    image: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    build:
      context: requirements/wordpress/
    ports:
      - "9000:9000"
    networks:
      - inception
    env_file:
      - .env    
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    build:
      context: requirements/nginx/
    ports: 
      - "443:443"
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env 
